export const questionData = [{"ko":"가장 행복한 순간은 언제였나요?","en":"What was your happiest moment?"},
{"ko":"여행 중에 가장 인상 깊었던 장소는 어디인가요?","en":"What is the most memorable trip you have been?"},
{"ko":"어릴 적 꿈 중 가장 기억에 남는 것은 무엇인가요?","en":"What was your childhood dream?"},
{"ko":"가장 친한 친구와의 추억 중 하나를 공유해주세요.","en":"What is your favorite memory with a friend?"},
{"ko":"가장 독특한 경험은 무엇이었나요?","en":"What experience stood out as the most exceptional?"},
{"ko":"최근에 발견한 새로운 취미나 관심사가 있나요?","en":"What is your new hobbies or interests you found recently?"},
{"ko":"인공지능을 얼만큼 신뢰하나요?","en":"Can we trust artificial intelligence?"},
{"ko":"내 인생에 영향을 준 책 3권을 소개해주세요.","en":"Which book(s) influenced you the most and why?"},
{"ko":"현재까지 인생에서 어떤 가르침을 얻었나요?","en":"What lessons have you learned from life?"},
{"ko":"추억이 담긴 음식이 있나요?","en":"What is a food that has strong memories linked to it?"},
{"ko":"어떤 도전을 극복한 경험이 있나요?","en":"What challenges have you overcome?"},
{"ko":"어떤 유명 인물과 만나고 싶나요? 그 이유는?","en":"Which famous person would you like to meet and why?"},
{"ko":"가장 중요하게 생각하는 가치는 무엇인가요?","en":"What are the most important personal values and why?"},
{"ko":"어떤 일에 대한 후회가 있나요?","en":"Do you have any regrets in life?"},
{"ko":"어떤 꿈을 이루기 위해 노력 중인가요?","en":"what goals are you trying to achieve?"},
{"ko":"나를 세 단어로 표현한다면 무엇이라고 할 수 있나요?","en":"Describe yourself in three words."},
{"ko":"지금까지의 인생 중 가장 큰 변화는 무엇이었나요?","en":"What was the biggest change in your life?"},
{"ko":"원하는 커리어 쌓기와 복권 당첨 중 무엇을 선택할건가요?","en":"Which would you choose, winning the lottery or working in a perfect job?"},
{"ko":"가장 어려웠던 결정은 무엇이었나요?","en":"Describe the most difficult decision you've ever made"},
{"ko":"어떤 것에 대해 자주 생각하게 되는지 알려주세요.","en":"Whar is something that you think about often?"},
{"ko":"타인을 이해하는 데 어떤 노력을 기울이나요?","en":"What is the best way to understand other people?"},
{"ko":"지난 5년 동안 어떻게 성장했다고 느끼나요?","en":"How have you grown or changed over the past 5 years?"},
{"ko":"여가 시간에 가장 자주 하는 활동은 무엇인가요?","en":"What do you like to do in your spare time?"},
{"ko":"미래에 이루고 싶은 큰 목표가 있나요?","en":"What are your long-term goals?"},
{"ko":"어떤 상황에서 가장 긴장되는지 알려주세요.","en":"What situations make your nervous?"},
{"ko":"과거로 돌아갈 수 있다면 어떤 일을 바꾸고 싶나요?","en":"Would you change the past of you could?"},
{"ko":"삶에서 가장 큰 원동력은 무엇인가요?","en":"What is the greatest driving force in your life?"},
{"ko":"가장 좋아하는 계절은 무엇인가요? 그 이유는?","en":"What is your favorite season and why?"},
{"ko":"가장 큰 업적이나 성과는 무엇인가요?","en":"What is your biggest achievement?"},
{"ko":"어떤 사람이 나에게 영향을 많이 주었나요?","en":"Who has influenced you the most?"},
{"ko":"가장 힘들게 극복한 도전은 무엇이었나요?","en":"What is the biggest life struggle you hope to overcome?"},
{"ko":"좋아하는 문구나 명언이 있나요?","en":"What is your favorite quote and why?"},
{"ko":"휴식을 취할 때 가장 좋아하는 방법은 무엇인가요?","en":"What is your best way to relax?"},
{"ko":"가장 감사하게 생각하는 것은 무엇인가요?","en":"What are you most grateful for?"},
{"ko":"미래에 이루고 싶은 여행 목록이 있나요?","en":"Do you have a travel bucket list?"},
{"ko":"어떤 경험을 통해 자신을 더 잘 이해하게 되었나요?","en":"What kind of life expereinces lead to the greatest self-understanding?"},
{"ko":"인생에서 얻은 가장 큰 교훈은 무엇인가요?","en":"What is the biggest lesson you have learned in life?"},
{"ko":"어떤 사회적 문제에 관심을 갖고 있나요?","en":"What social issues are you interested in?"},
{"ko":"가장 좋아하는 과거 추억 중 하나를 공유해주세요.","en":"What is your favorite childhood memory?"},
{"ko":"가장 자주 하는 스트레스 해소 방법은 무엇인가요?","en":"How do you deal with stress?"},
{"ko":"나의 성격과 특징을 간단히 설명해보세요.","en":"Briefly explain your personality and charactersitics."},
{"ko":"어떤 일에 대해 자주 꿈을 꾸나요?","en":"What do you often dream about?"},
{"ko":"가장 독특한 여행 경험을 알려주세요.","en":"What was the most memorable travel experience?"},
{"ko":"가장 중요하게 생각하는 가족 구성원은 누구인가요?","en":"Which family member has the most influence in life?"},
{"ko":"가장 흥미로운 수업이나 교육 경험은 무엇이었나요?","en":"What is the most interesting education or class you've ever took?"},
{"ko":"자신의 장점과 단점을 알려주세요.","en":"What is your strength and weakness?"},
{"ko":"가장 자주 가는 장소나 공간은 어디인가요?","en":"What place do you most like to visit and why?"},
{"ko":"가장 큰 꿈이 이루어진다면 어떤 모습일까요?","en":"What would it be like if your dreams come true?"},
{"ko":"가장 좋아하는 책이나 작가가 있나요?","en":"Do you have a favorite book or author?"},
{"ko":"자신을 동물로 비유한다면 어떤 동물이 될 것 같나요?","en":"What animal would you use to describe yourself and why?"},
{"ko":"가장 인상 깊었던 영화는 무엇이었나요?","en":"What is your go to movie and why?"},
{"ko":"지금까지 가장 행복한 순간은 언제였나요?","en":"What was the happiest moment in your life?"},
{"ko":"미래에 이루고 싶은 직업이나 경력이 있나요?","en":"What are your career goals?"},
{"ko":"가장 좋아하는 색깔이 무엇인가요? 그 이유는?","en":"What is your favorite color and why?"},
{"ko":"지금까지의 삶에서 가장 큰 후회는 무엇이었나요?","en":"What is your biggest regret?"},
{"ko":"어떤 것에 대해 끊임없이 배우고 싶은 욕구를 느끼나요?","en":"Do you feel the urge to learn something fully?"},
{"ko":"어떤 사람과 함께 시간을 보내는 것을 즐기나요?","en":"What kind of person do you enjoy spending time with?"},
{"ko":"가장 가까운 미래에 이루고 싶은 계획은 무엇인가요?","en":"What are your plans for the nearest future?"},
{"ko":"가장 특별한 선물을 받은 적이 있나요?","en":"What is the most meaningful gift ever received?"},
{"ko":"다른 사람들에게 어떤 영향을 주고 싶나요?","en":"How would you like to influence others?"},
{"ko":"지금까지 겪은 어떤 도전이 가장 큰 자부심이 되나요?","en":"What challenges are you most proud of overcoming?"},
{"ko":"미래의 자녀들에게 어떤 가르침을 전하고 싶나요?","en":"What would you want to teach the children of the future?"},
{"ko":"가장 좋아하는 날씨나 기후는 어떤 것인가요?","en":"What is your favorite weather or climate?"},
{"ko":"시간여행자가 된다면 어느 시기로 돌아가고 싶나요?","en":"If you could time travel, which period would you go back to?"},
{"ko":"나를 변화시키고 싶은 점이 있다면 무엇인가요?","en":"What do you want to change about yourself?"},
{"ko":"어떤 문화나 국가에 특별한 관심을 갖고 있나요?","en":"What culture or country are you particularly interested in?"},
{"ko":"가장 좋아하는 외부 활동이나 운동이 무엇인가요?","en":"What is your favorite outdoor activity or exercise?"},
{"ko":"어떤 상황에서 큰 용기를 발휘했던 적이 있나요?","en":"In what situation did you show your courage?"},
{"ko":"다른 사람에게 어떤 영감을 받거나 느낀 적이 있나요?","en":"Have you ever been inspired by someone else?"},
{"ko":"가장 특별한 가족 행사나 이벤트는 무엇인가요?","en":"What is your favorite family tradition?"},
{"ko":"어떤 상황에서 자주 웃게 되나요?","en":"What kind of things make you laugh?"},
{"ko":"나만의 자랑스러운 능력이나 특기가 있나요?","en":"What are you most proud of?"},
{"ko":"어떤 일에 대해 꾸준한 열정을 가지고 있나요?","en":"What are you passionate about?"},
{"ko":"가장 소중한 물건이나 사물은 무엇인가요?","en":"What is the most precious thing in your life?"},
{"ko":"어떤 종류의 예술이나 창작 활동에 흥미를 갖고 있나요?","en":"What type of creative activities are you interested in?"},
{"ko":"다른 사람들과 어떤 종류의 대화를 주로 나누고 싶나요?","en":"What kinds of conversations do you like the most?"},
{"ko":"어떤 상황에서 가장 창의적인 아이디어를 떠올리나요?","en":"How do you come up with creative ideas?"},
{"ko":"인생에 크게 영향을 미친 사건이나 경험은 무엇인가요?","en":"What are significant events that happened in your life?"},
{"ko":"어떤 종류의 여행을 선호하나요?","en":"What kind of traveler are you?"},
{"ko":"다른 사람들이 나를 어떻게 기억하길 바라나요?","en":"How would you want to be remembered?"},
{"ko":"어떤 형태의 사회봉사나 기부 활동에 참여하고 싶나요?","en":"Which community services would you like to participate?"},
{"ko":"어떤 긍정적인 습관을 현재까지 형성한 적이 있나요?","en":"What are your positive habits?"},
{"ko":"목표를 이루기 위해 가장 큰 장애물은 무엇인가요?","en":"What is the potential obstacle in achieving your goal?"},
{"ko":"지금 이 순간의 감정이나 생각을 표현해보세요.","en":"Express your feelings or thoughts at this moment."},
{"ko":"어떤 종류의 새로운 경험을 해보고 싶나요?","en":"What kind of new experience do you want to have?"},
{"ko":"가장 좋아하는 영어 표현이나 문구가 있나요?","en":"What are your favorite expressions?"},
{"ko":"나를 더 발전시키기 위해 노력하고 있는 점이 있나요?","en":"What do you want to improve on yourself?"},
{"ko":"다른 사람들과 함께 할 때 어떤 역할을 주로 맡게 되나요?","en":"What role do you usually play when you're with others?"},
{"ko":"역경을 헤쳐 나가는 데 가장 효과적인 전략이 있나요?","en":"What is the most effective strategy to overcome adversity?"},
{"ko":"어떤 활동을 하면서 가장 자주 '나 자신' 이라고 느껴지나요?","en":"What kind of activities do you feel "},
{"ko":"어떤 상황에서 불안 또는 두려움을 느끼게 되나요?","en":"In what situations do you feel anxious or afraid?"},
{"ko":"어떤 종류의 환경 문제에 대해 관심을 갖고 있나요?","en":"Which environmental topics are you interested in?"},
{"ko":"대화에서 가장 중요하게 생각하는 것은 무엇인가요?","en":"What is the most important thing in a conversation?"},
{"ko":"닮고 싶은 사람, 롤모델이 있나요?","en":"Do you have a role model?"},
{"ko":"미래에 대해 가장 걱정되는 것은 무엇인가요?","en":"What worries you the most about the future?"},
{"ko":"나에게 성공이란 무엇인가요?","en":"How would you define success?"},
{"ko":"인생에서 몇 명의 친구를 믿을 수 있나요?","en":"How many friends can you trust in your life?"},
{"ko":"사랑하는 사람을 위해 법을 어길 수 있나요?","en":"Can you break the law for someone you love?"},
{"ko":"나의 사명감은 무엇인가요?","en":"What is your sense of duty?"},
{"ko":"변하지 않았으면 하는 나의 모습은 무엇인가요?","en":"What is the one thing that you never want to change?"},
{"ko":"책임을 진다는 것은 어떤 의미인가요?","en":"What does it mean to take responsibility?"},
{"ko":"내 가치관과 일관된 삶을 살고 있나요?","en":"Are you living by your values?"},
{"ko":"나의 가치관을 지키는데 방해가 되었던 것은 무엇인가요?","en":"What interfered with your personal values?"},
{"ko":"인간관계에서 가장 중요한 세가지는 무엇인가요?","en":"What are the three most important things in human relationships?"},
{"ko":"최근에 내가 다른 사람과 나 자신에게 좋은 사람이었나요?","en":"Have I been a good person to other people and myself lately?"},
{"ko":"나를 위한 사랑이란 무엇인가요?","en":"What is love to you?"},
{"ko":"5년 후 무엇을 하고 싶나요?","en":"What do you want to do in 5 years?"},
{"ko":"완벽한 날에 대한 나의 정의는 무엇인가요?","en":"What is my definition of a perfect day?"},
{"ko":"스스로 만든 한계에 갇혀 있지는 않나요?","en":"Aren't you stuck in your own self-made limit?"},
{"ko":"나의 묘비에 어떤 글을 새길건가요?","en":"What do you want engraved on your tombstone?"},
{"ko":"과거, 현재, 미래 중 나는 어디에 살고 있나요?","en":"Past, present, or future: where do you usually live?"},
{"ko":"혹시 스스로를 미워하고 있지는 않나요?","en":"How do you deal with self-hatred?"},
{"ko":"하늘을 날아서 가보고 싶은 곳이 있나요?","en":"If you could fly, where would you go?"},
{"ko":"이번 생에 꼭 이루고 싶은 3가지는 무엇인가요?","en":"What are three things you want to achieve in this life?"},
{"ko":"가장 보고 싶은 사람이 있다면, 무슨 말을 전하고 싶나요?","en":"What do you want to say to the person you miss?"},
{"ko":"나는 나 자신과 친하다고 생각하나요?","en":"Do you feel like you truly know yourself?"},
{"ko":"삶의 질을 높여준 제품 2개를 꼽아보자면 무엇인가요?","en":"What are the two products that have improved the quality of life?"},
{"ko":"살면서 고친 버릇이나 성격은 무엇인가요?","en":"What is a habit or personality that you have fixed?"},
{"ko":"내가 했던 최악의 거짓말은 뭐였나요?","en":"What was the worst lie you've ever told?"},
{"ko":"나의 인생을 네컷만화로 그린다면 내용을 바꾸고 싶나요?","en":"If you were to draw life in a 4-cut cartoon, would you change the content?"},
{"ko":"세상에서 단 한가지를 바꿀 수 있다면 무엇일까요?","en":"If you could change one thing in the world, what would it be?"},
{"ko":"좋은 리더가 가져야 할 능력은 무엇인가요?","en":"What abilities should a good leader have?"},
{"ko":"정말 하고 싶었는데 못했던 일이 있나요?","en":"What is something you've always wanted to do but couldn't?"},
{"ko":"건강을 유지하기 위해서 무슨일을 하나요?","en":"how do you maintain your health?"},
{"ko":"매일 가장 많이 생각하는 세 가지는 무엇인가요?","en":"What three things do you think of the most each day?"},
{"ko":"돈과 행복의 관계에 대한 본인만의 철학이 있나요?","en":"Can money buy happiness?"},
{"ko":"삶의 균형을 유지/파괴하는데 돈은 어떤 역할을 하나요?","en":"How can money help to maintain or destroy life structure?"},
{"ko":"소셜 미디어를 사용하며 삶에 어떤 변화가 있었나요?","en":"How have your behaviors changed since you started using social media?"},
{"ko":"나는 어떤 미디어 컨텐츠를 자주 보나요?","en":"What type of media content do you like to watch?"},
{"ko":"크리에이터가 된다면, 어떤 정보를 공유하고 싶은가요?","en":"If you become a creator, what information do you want to share?"},
{"ko":"대면 혹은 비대면 소통 중 어느 것을 선호하나요?","en":"Do you prefer face-to-face or remote communication?"},
{"ko":"온라인 익명성의 장단점은 무엇이라 생각하나요?","en":"What are the pros and cons of online anonymity?"},
{"ko":"지금의 삶에 어느 정도 만족하나요?","en":"How satisfied are you with your current life?"},
{"ko":"나는 부모님의 어떤 점을 닮았나요?","en":"what personality traits did you inherit from your parents?"},
{"ko":"나의 이름엔 어떤 뜻이 있나요? 그 의도대로 살고 있나요?","en":"What does your name reveal about you?"},
{"ko":"지금의 나에게 던지고 싶은 질문은 무엇인가요?","en":"What do you want to ask about yourself?"},
{"ko":"이번 주, 삶을 마감한다면 하고 싶은 일이 있나요?","en":"What will you do if you know you'll die next week?"},
{"ko":"아무에게도 말 못한 비밀이 있나요?","en":"What is a secret you've never told anyone?"},
{"ko":"나에게 결혼이란 무엇을 의미하나요?","en":"What does marriage mean to you?"},
{"ko":"인생의 버킷 리스트가 있나요?","en":"Do you have a bucket list?"},
{"ko":"남들이 알면 흥미로워할 나만의 TMI는 무엇인가요?","en":"What is your own TMI that others would find interesting?"},
{"ko":"남들이 생각하는 나와 내가 생각하는 나는 누구인가요?","en":"How do you perceive yourself, and how do others perceive you?"},
{"ko":"좌절을 경험한 사람에게 해주고 싶은 말이 있나요?","en":"What would you say to someone who is frustrated?"},
{"ko":"삶이 재밌다고 느껴지는 순간은 언제인가요?","en":"How do you make things interesting?"},
{"ko":"현재의 내가 가장 잘하고 싶은 것은 무엇인가요?","en":"How do you make the most out of life?"},
{"ko":"사무실이나 부엌 창문에서 볼 수 있는 가장 흥미로운 것은 무엇인가요?","en":"What is the most interesting thing to see in an office or kitchen window?"},
{"ko":"내가 좋아하는 향이 있나요? 그 이유는?","en":"What is your favorite scent and why?"},
{"ko":"나와 잘 맞는 사람들의 공통점이 있나요?","en":"Do your friends have things in common?"},
{"ko":"사람은 변할 수 있다고 생각하나요?","en":"Do you think people can change?"},
{"ko":"힘들때 혹은 기쁠때 듣는 노래가 있나요?","en":"What songs get you through tough times?"},
{"ko":"미워했던 사람을 용서한 적 있나요?","en":"How did you forgive someone you hate the most?"},
{"ko":"외모지상주의 사상에 대해 어떻게 생각하시나요?","en":"How do you feel about lookism?"},
{"ko":"죽음이 무엇이라고 생각하나요?","en":"What do you think of death?"},
{"ko":"자기 자신에게 거짓말을 한 적이 있나요?","en":"Have you ever lied to yourself?"},
{"ko":"인생에서 두려움과 고통은 어떤 역할을 하나요?","en":"What role do fear and pain play in life?"},
{"ko":"성숙은 무엇을 의미하나요?","en":"What does it mean to be mature?"},
{"ko":"나와 완전히 반대되는 사람은 어떤 사람인가요?","en":"What kind of person is the complete opposite of me?"},
{"ko":"다른 사람을 위해 목숨을 바칠 수 있나요?","en":"Would you ever give up your life to save someone else?"},
{"ko":"마지막으로 새로운 것을 시도한 적이 언제였나요?","en":"When was the last time you tried something new?"},
{"ko":"여가시간을 어떻게 보내고 싶나요?","en":"How do you want to spend your free time?"},
{"ko":"선과 악의 기준은 어디에 있나요?","en":"What is the standard for good and evil?"},
{"ko":"현재 이 사회에는 무엇이 부족하다고 생각하나요?","en":"What do you think our society is lacking?"},
{"ko":"호기심을 불러 일으키는 것이 있나요?","en":"Is there anything that intrigues you?"}]