[[redirects]]
from = "/proxy/*"
to = "https://api.slayoutliers.click/:splat"  
status = 200
force = true
headers = {X-From = "Netlify"}

[[headers]]
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "*"