
export let getData = 
[
    {"id":1,"answer":"What do I want most in life?"},
    {"id":2,"answer":"If you could give one piece of advice to a newborn child, what would it be?"},
    {"id":3,"answer":"If today were the last day of my life, what would I want to do?"},
    {"id":4,"answer":"Have you ever witnessed a small act of kindness that you will never forget?"},
    {"id":5,"answer":"Am I happy right now?"},
    {"id":6,"answer":"What worries me the most about the future?"},
    {"id":7,"answer":"What does success mean to me?"},
    {"id":8,"answer":"Do I think it's worse to fail or to never try at all?"},
    {"id":9,"answer":"Who has had the greatest impact on my life?"},
    {"id":10,"answer":"How many friends can I truly trust in my life?"},
    {"id":11,"answer":"Is there something about myself that I want to change?"},
    {"id":12,"answer":"Would it be okay to break the law to save a loved one?"},
    {"id":13,"answer":"What is my sense of mission?"},
    {"id":14,"answer":"What is one thing I want others to remember about me when my life ends?"},
    {"id":15,"answer":"Is it really important what others think of me?"},
    {"id":16,"answer":"What is one aspect of myself that I never want to change?"},
    {"id":17,"answer":"What was the happiest moment of my life and why?"},
    {"id":18,"answer":"What was the most difficult moment of my life and why?"},
    {"id":19,"answer":"What are my strengths?"},
    {"id":20,"answer":"What are my weaknesses?"},
    {"id":21,"answer":"What do I want to know more about myself?"},
    {"id":22,"answer":"What does authenticity mean to me?"},
    {"id":23,"answer":"What does responsibility mean to me?"},
    {"id":24,"answer":"What goals do I want to achieve this year?"},
    {"id":25,"answer":"What is the best decision I have made and what is the most regrettable decision?"},
    {"id":26,"answer":"What is my life's motto (values, beliefs, etc.)? Am I true to my values?"},
    {"id":27,"answer":"What has helped or hindered me in upholding my values?"},
    {"id":28,"answer":"Do I remember a time when my values and actions brought comfort and joy to others?"},
    {"id":29,"answer":"What does home mean to me?"},
    {"id":30,"answer":"What are the three most important things in human relationships?"},
    {"id":31,"answer":"Have I been a good person to others and myself recently?"},
    {"id":32,"answer":"What does love for myself mean?"},
    {"id":33,"answer":"What do I want to be doing in five years?"},
    {"id":34,"answer":"What is my definition of a perfect day?"},
    {"id":35,"answer":"What am I afraid of?"},
    {"id":36,"answer":"What do family and friends mean to me?"},
    {"id":37,"answer":"What are the five things I never want to lose while I'm alive?"},
    {"id":38,"answer":"Am I trapped by self-imposed limitations?"},
    {"id":39,"answer":"What is my current worry? Will this worry still matter on the last day of my life?"},
    {"id":40,"answer":"What would I want to be written on my tombstone?"},
    {"id":41,"answer":"Do I live in the past, present, or future?"},
    {"id":42,"answer":"Do I hate myself?"},
    {"id":43,"answer":"Do I have a childhood memory that comes to mind when I think of spring?"},
    {"id":44,"answer":"Is there a place I would like to fly to?"},
    {"id":45,"answer":"What was my childhood dream?"},
    {"id":46,"answer":"If I could make three wishes come true, what would they be?"},
    {"id":47,"answer":"What was my favorite game when I was a child?"},
    {"id":48,"answer":"How did I overcome difficult moments and what did I learn from them?"},
    {"id":49,"answer":"Is there someone I want to see the most in my life? What gift or words would I like to give them?"},
    {"id":50,"answer":"Do I know myself well and am I close to myself?"},
    {"id":51,"answer":"What are two products that have improved my quality of life?"},
    {"id":52,"answer":"What habits or personality traits have I changed in my life? What prompted the change?"},
    {"id":53,"answer":"Who is my life mentor or role model?"},
    {"id":54,"answer":"What does it mean to be alive? Have I felt alive in the past few months?"},
    {"id":55,"answer":"Do I want to be or have I been an important person to someone today?"},
    {"id":56,"answer":"If I made my life into a four-panel comic, would I want to change the content?"},
    {"id":57,"answer":"If I could change one thing in the world, what would it be?"},
    {"id":58,"answer":"What abilities should a good leader have? What are the pros and cons of these abilities?"},
    {"id":59,"answer":"What are some moments when my instant decisions changed my life?"},
    {"id":60,"answer":"Who are the people I have valued the most in my life? What do they have in common?"},
    {"id":61,"answer":"Is there something I really wanted to do but couldn't? What was the reason I couldn't do it?"},
    {"id":62,"answer":"What do you think is the difference in speaking habits between the rich and the poor?"}
]